# Site settings
title: "Song Huang's Homepage"
email: dr.guangtou@gmail.com 
url: https://dr-guangtou.github.io
description: "This is Song Huang's homepage for research related stuff." 

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary:   2b8cbe #80B3FF
  secondary: a8ddb5 #FD6E8A
  secondary-dark: 233140 #A2122F
# primary: 18bc9c #80B3FF
# secondary: 2c3e50 #FD6E8A
# secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Song Huang  
  location: Tokyo 
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/dr_guangtou
  - title: github
    url: http://github.com/dr-guangtou
  - title: google-plus 
    url: https://plus.google.com/+SongHuangAstro 
  - title: weibo 
    url: http://www.weibo.com/1764919567

# Postal address (add as many lines as necessary)
address:
  - line: IPMU, University of Tokyo
  - line: 6-2-3, Kashiwanoha, 
  - line: Kashiwa, Chiba, Japan

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
